[package]
name = "guessing_game"
authors = ["Brian Obot"]
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "Learnging"
path = "src/8_suggested_programs/pigin_english_converter.rs"
